### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by Macadoshis**
- Update xpath elements to latest DOM of IG (2024-11-28)
- Update chromedriver.exe to latest
- Fix path to avoid warning
- Add current datetime to log messages (to assert velocity of script)
- Also acknowledge users with warnings (already blocked, account deleted)

### CODE REVIEW

**Comment by Merl1m** [comment]
I have send an update to your email! Look into that and do another pull request!!

**Comment by Macadoshis** [comment]
Hi @Merl1m 

As of your email. 

1. I did that mistake on my `main` branch not the `fixes` branch which is the source of this pull request. As shown in https://github.com/Merl1m/Instagram_Block_Automation/pull/1/files there's no change on those lines. But ty for noticing I'll force push my `main` asap but it has no consequence for this pull request to be closed. 
2. What error exactly please ? I have no error in my console (I run the script on windows 11, py 2.7.13), all I did is prepending the current time in the log message, and it's the same addition both for an account blocked or warning an already blocked.

Anyway, no reason to close instead of rejecting with inline comments the current PR.
Please write an inline comment on what is exactly failing on my log message change. 

Ty

**Comment by Merl1m** [comment]
I am terribly sorry about that. In that case, let me test the fixes branch code, and if it is working smoothly, then soon, I will merge it. With a quick review, the syntax error is present in this one as well

Line 188
Line 193
Line 198

These lines, you have tried to use double quotes inside double quotes, which would cause it to split into 2 separate strings with the %y... in between. Try using single quotes for %Y-%m.... part.

**Comment by Merl1m** [comment]
Also, update the top line, version 1.8 to 1.9 and another two comments below that with your github username or so to indicate you modified it.

**Comment by Merl1m** [comment]
Okay, I get it, so you used python 2, The syntax error is due to the fact I tried to run it on python 3. No worries, I will merge it as soon as I test it, Consider it done in a hour.

**Comment by Merl1m** [comment]
Thank you for improvising the code, feel free to update the code when the DOM of Instagram changes again.

**Comment by Macadoshis** [comment]
Thanks for the merge. (Indeed my `main` branch, which is the default when you cloned my fork, is just garbage for personal use (my creds commited by mistake, and hard-written updates about delays to be more brutal on the wait time so I could block 2000+ accounts within 3 hours) ).
Agreed, I should have used quotes, and I can't remember why I did not in the first place.
If it fails for py3, please fix it from your side :)

keep it up fam 🥇

**Pull request merged**
